### ISSUE TITLE
Using class attribute on component in TSX

### ISSUE THREAD

**Issue by dvic** [vuejs/composition-api#173]
Anyone else having compile errors using the `class` attribute on components created with `createComponent`?

**Comment by LinusBorg** [comment]
I personally do not. You might get a (better) response if you provided a reproduction of the issue for us to look at.

**Comment by dvic** [comment]
Sure, here is an example: https://codesandbox.io/s/github/dvic/vue-composition-api-tsx

The problem can be seen in `components/foo.tsx`. It seems that the compile errors only becomes apparent when using TSX files.

![image](https://user-images.githubusercontent.com/1214337/68214698-36e04200-ffde-11e9-96ce-8fbbc184781c.png)

**Comment by davvelsan** [comment]
I am having a different problem, but possibly related. In your case, it seems `ts` is asking for a `class` property in the component... not sure why it does that.

```tsx
import { createComponent } from "@vue/composition-api";

export const Foo = createComponent({
  setup() {
    return () => {
      return (
        <div>
          <div>This is foo</div>
          <Bar class="some-class" />
        </div>
      );
    };
  }
});

export const Bar = createComponent({
  props: {
    class: String
  },
  setup() {
    return () => {
      return <div>This is bar.</div>;
    };
  }
});
```

In my case, I get this error:

> Type '{ class: string; filename: string; }' is not assignable to type 'ExtractPropTypes<{ filename: { type: StringConstructor; required: true; }; }, false>'.
  Property 'class' does not exist on type 'ExtractPropTypes<{ filename: { type: StringConstructor; required: true; }; }, false>'.

It also goes away by creating a `class` prop in the component. I think this is an editor/ts thing, since everything compiles fine and the class is added to the child component.

**Comment by davvelsan** [comment]
Adding the property declaration to `shims-tsx.d.ts` also fixes it:

```ts
import { VNode } from 'vue';
import { ComponentRenderProxy } from '@vue/composition-api';

declare global {
  namespace JSX {
    interface Element extends VNode {}
    interface ElementClass extends ComponentRenderProxy {}
    interface ElementAttributesProperty {
      $props: any; // specify the property name to use
      $class: string;
    }
    interface IntrinsicElements {
      [elem: string]: any
    }
  }
}
```

In the case of `class` it might need a few more types covered?

**Comment by davvelsan** [comment]
A follow-up post. I found an [SO question](https://stackoverflow.com/questions/52973485/unable-to-use-html-attributes-on-custom-components-in-tsx) from a year ago that is directly related to my issue. Also, I've been taking a peek inside `component.d.ts` and `componentProps.d.ts`, which is where all the relevant type definitions related to my problem seem to be declared. But I haven't had much luck determining where the problem is so far.

At this point I'm not sure whether I should start a new issue. I'm not sure @dvic is referring to the same problem (although they do appear related), so I don't want to hijack his thread.

@LinusBorg, any chance you may weigh in again, in light of my recent posts? Should I move my stuff to a new issue?

**Comment by vaiil** [comment]
@LinusBorg 
I also have a problem with class property:
`Property 'class' does not exist on type 'ExtractPropTypes<{ ... }, false>`

I try to rewrite `ComponentRenderProxy`'s `$props` to something like that:
```ts
export declare type ComponentRenderProxy<P = {}, S = {}, PublicProps = P> = {
...
    $props: PublicProps | {
            class?: string | null | (string | null)[]
            id?: string
            key?: string | number
          } | {props: PublicProps};
   ...
} & P & S;
```
It solves the problem, but I don't know how I can redeclare `ComponentRenderProxy` using shims.

**Comment by antfu** [comment]
I am going to close this now as it's kind inactive for a while and the reproduce link gets expired.

If you still facing issues with JSX/TSX, please check if it's a problem of https://github.com/luwanquan/babel-preset-vca-jsx first. Thanks.

**Comment by Malek-Almutairi** [comment]
![image](https://github.com/vuejs/composition-api/assets/158858176/cfe7e2f2-7be2-4f05-8f9b-486358e03975)
can any one help me
