### ISSUE TITLE
Computed: unexcepted behaviour when using set

### ISSUE THREAD

**Issue by maximelebreton** [vuejs/composition-api#174]
Hello,
as mentionned by @zerobias in this discussion (https://github.com/zerobias/effector/issues/237#issuecomment-548527738), there seems to be a bug on `computed` implementation, when using `set` inside. 

Here is the reproduction case: 
https://codesandbox.io/s/vue-composition-api-bug-with-computed-when-using-set-e0fd2

a `@debugger` breakpoint shows that this behaviour appears inside the **vue** `flushCallbacks` function call, if this can help...: https://github.com/vuejs/vue/blob/d7d8ff06b70cf1a2345e3839c503fdb08d75ba49/src/core/util/next-tick.js#L13

With **Vue** `2.5.22` and **@vue/composition-api** `0.3.2`

Oh, and I really enjoy the composition api!

**Comment by LinusBorg** [comment]
the computed's `get`method references a non-reactive `let` variable called `input`. That means the getter will never update since the computed has no reactive dependency that would trigger a re-evaluation.

**Comment by zerobias** [comment]
This is not about `get` method, this is an issue with `set`, in which any assignment to `ref.value` leads to odd behavior: looks like component reset itself.
```vue
<template>
  <div>
    <input v-model="state.search">

    <div v-if="state.searchRef">{{state.searchRef}}</div>
  </div>
</template>

<script>
import { reactive, ref, computed, createComponent } from "@vue/composition-api";
export default createComponent({
  setup(props, context) {
    const search = ref("ok");
    let input = "hey";
    return {
      state: reactive({
        searchRef: search,
        search: computed({
          get: () => input,
          set(value) {
            input = value;
            // this assignment ruin everything
            search.value = value;
          }
        })
      })
    };
  }
})
</script>
```

**Comment by LinusBorg** [comment]
You still haven't explained what the perceived problem is.

"Odd behaviour" and "ruins everything" don't help me understand your problem.

Please describe exactly what you want to happen vs. what is actually happening.

**Comment by maximelebreton** [comment]
As the demo shows only a `v-model`, I supposed the expected behavior was quite implicit:
[model-text.spec.js](https://github.com/vuejs/vue/blob/0fb03b7831693b4abc90dd0bfe971c36c02d82a6/test/unit/features/directives/model-text.spec.js#L4-L20)
```js
describe('Directive v-model text', () => {
  it('should update value both ways', done => {
  // ...
```

But maybe we need a **real** context case:
I encoutered this problem first when I tried to recreate the **[vue-x two way computed property recipe](https://vuex.vuejs.org/guide/forms.html#two-way-computed-property)** with **[effector](http://effector.now.sh)** _(a state manager I mainly choose because **Vuex** isn't Typescript ready)_.

Here is the case:
**https://codesandbox.io/s/effector-with-vue-e8mjo**

```js
// search.js
import { createStore, createEvent } from 'effector';

const searchInputChanged = createEvent();
const searchTriggered = createEvent();
const textUpdated = createEvent();

const $search = createStore('hey').on(searchInputChanged, (state, payload) => payload);
const $text = createStore('').on(textUpdated, (state, payload) => payload);

searchTriggered.watch(() => {
  textUpdated(`${$search.getState()} triggered at ${new Date().toLocaleTimeString()} `);
});
```

```vue
// search.vue
<template>
  <div><input v-model="state.search"><div>{{$text}}</div></div>
</template>

<script>
...
    const state = reactive({
      search: computed({
        get: $search.getState,
        set: searchInputChanged
      })
    });

    $search.watch(state => {
      searchTriggered();
    });
...
</script>
```
So as the spec says:
- the `v-model` **should update value both ways**, like in the [Vuex recipe](https://vuex.vuejs.org/guide/forms.html#two-way-computed-property)
- but in the above example, the `v-model` seems to **resets itself** when using a **computed property** wich refers to a **reactive** (but non-**Vue**) value.

We talked about it [here](https://github.com/zerobias/effector/issues/237) with @zerobias, and he reduced the case [to this](https://codesandbox.io/s/vue-composition-api-bug-with-computed-when-using-set-e0fd2) for a better understanding of the problem, which does not seem to be related to **effector**.

I hope it's now more clear for you,

Thanks for your help

**Comment by LinusBorg** [comment]
Thanks. 

> but in the above example, the v-model seems to resets itself when using a computed property wich refers to a reactive (but non-Vue) value.

Right. effector may also call their system "reactive", but it's not using Vue's reactivity system, so Vue can't detect when effector `"reacts" to anything. Vue can't detect things changing just because they also declare themselves to be "reactive". It can only detect changes within its own reactivity system Which is why you were able to reproduce the problem without effector as well.

>  does not seem to be related to effector.

### So why does it happen?

My answer is still the same. 

1 The computed `get` return value is cached as long as no reactive dependencies change. 
2. state from effector is not reactive, as far as Vue can tell. 
3. So when the component re-renders after the input by the user, it will re-apply the *old* value from the getter to the input.

As far as Vue is concerned,  `$search.getState` never changed. It still has the original value.

The same reason applies to thje reduced case: you changed a non-reactive, local `let` variable called `input`, but Vue can't detect that. It's not reactive

In both scenarios, `search` will always return the initial value forever, *because that's how computed properties work*: They cache their result until a reactive dependency changes. if there's no reactive depenency, the value will never update.

When the `input` is a ref, everything works like you expect:

```javascript
export default createComponent({
  setup(props, context) {
    const search = ref("ok");
    const input = ref("hey");
    return {
      state: reactive({
        searchRef: search,
        search: computed({
          get: () => input.value,
          set(value) {
            input.value = value;
            // this assignment ruin everything
            search.value = value;
          }
        })
      })
    };
  }
});
```

You can create the same effect with the old API, it's not related in any way to Vue.
