### ISSUE TITLE
onUnmounted called in keep-alive components

### ISSUE THREAD

**Issue by doncatnip** [vuejs/composition-api#178]
When using keep-alive there does not seem to be a way to trigger something on destroyed. onUnmounted gets called every time I navigate away from that component, even though the component persists due to keep-alive. onDestroyed does not exist in the composition API. An oversight ?
(edit) ~~It is a nested component within other tabs that do not have keep-alive. I assumed in this case nested childs will get destroyed when navigating away from the parent component. I guess that isn't the case and so there is no need for an onDestroyed.~~

**Comment by doncatnip** [comment]
Reopening because after a bit of testing there really seems to be a lifecycle hook missing for this case. onUnmounted does not suffice. There need to be a hook that is called *once* the component is destroyed.

**Comment by LinusBorg** [comment]
The issue seems to be this line:

https://github.com/vuejs/composition-api/blob/1672b6e214adb50a22e525c18cc9098953598024/src/apis/lifecycle.ts#L37

Where the hook of `onUnmounted` is applied to both the `destroyed` and `deactivated` hooks.

This was appearantly done on purpose by @liximomo "to increase compatibility with the rfc" (according to the commit message from the blame for that line), but it could be that this is no longer accurate, not sure from the top of my head.

**Comment by doncatnip** [comment]
If this is in accordance to the RFC, then the RFC should be revisited.
https://vue-composition-api-rfc.netlify.com/api.html#lifecycle-hooks states:
destroyed -> onUnmounted
destroyed and deactivated have two distinct use cases and should not be merged.

**Comment by LinusBorg** [comment]
Yeah I'd rate this a bug. The options API doesn't have a similar API, and there's nothing about `deactivated` in the RFC.
