### ISSUE TITLE
Array value for vuex getter lost reactivity via setup()

### ISSUE THREAD

**Issue by isnifer** [vuejs/composition-api#186]
I started to rewrite my app to `composition-api`. Found that **vuex** getter **_array_** value **lost** reactivity via `setup()`.
I created an example https://codesandbox.io/s/vue-template-kz5t2.
You need just click on the button to see the difference between two behaviours.

**Comment by isnifer** [comment]
@liximomo any thoughts?

**Comment by LinusBorg** [comment]
you just return the getter's result, which is a plain array. There's nothing reactive about the `demoArray` in setup. 

This implementation works better and doesn't use any internal API:

```javascript
export function useGetters(namespace, getters) {
  // eslint-disable-next-line
  return getters.reduce((getters, getter) => {
    getters[getter] = computed(() => store.getters[`${namespace}/${getter}`]);
    return getters;
  }, {});
}
```

**Comment by isnifer** [comment]
@LinusBorg I wanted to go away from this vuex-way declaration.
About reactivity – why do I see some Observer at array internals in this case?
Why getters are not reactive?

**Comment by LinusBorg** [comment]
The array itself may be reactive, meaning: mutations of this array will be ovserved.

But every time the getter updates, it creates a new array, and since `setup` runs only once, the `demoArray` const variable will always reference the first array.

when you use `mapGetters`, you add it to the `computed` option of your component, precicely so that a change/update of the getter's return value can be reacted to.

I did the same thing, in principal, by returning a `computed()` ref in my code above.

**Comment by isnifer** [comment]
@LinusBorg thanks for the clarification
