### ISSUE TITLE
throw error when use Object.freeze() to return value  in setup

### ISSUE THREAD

**Issue by houfeng0923** [vuejs/composition-api#233]
this case is in vue2.x ,  and throw error below: 

> Property or method "city" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

code like this: 

```
<template>
{{city.name}}
</template>
<script>
import { createComponent } from '@vue/composition-api';
export default createComponent({
  setup() {
    const city = Object.freeze({name: 'dl'});
    return {city};
  }
});
</script>
``` 

so,  why setup() not allow return freeze property ? and how to use freeze object in hook api ? 

thank u

**Comment by RANGELJ** [comment]
I am not sure the use case, my guess is that your object named "city" is not reactive state because you want it to be a constant,  and because it is not reactive state, it cannot be used in a template, if you are trying to use it as a constant, it is better to use directly in the template:
`
<template>
dl
</template>
`

**Comment by houfeng0923** [comment]
in vue2.x,  we can make model frozen for performance ;
like [demo](https://codesandbox.io/s/vue-composite-api-test-e2fxq)

but , in `setup` way, why not ?
