### ISSUE TITLE
Missing UnwrapRef export

### ISSUE THREAD

**Issue by spaceemotion** [vuejs/composition-api#247]
I wanted to switch a couple fields that belong together from individual `ref()`'s to a single `reactive()`. Since I am using TypeScript, I tried to import the UnwrapRef type, but instead of using the main import, it redirected me to its full path instead:

I can import this:
```js
import { Ref } from '@vue/composition-api';
```

but need to do this for UnwrapRef:
```js
import { UnwrapRef } from '@vue/composition-api/dist/reactivity/index.d';
```

has this been an oversight, or is there a reason (like, "probably don't want to use reactive at all")?

Edit: I also noticed that `Refs` seems to be missing?

**Comment by LinusBorg** [comment]
I'm no sure why you'd need that type.

**Comment by pikax** [comment]
Having it exported, would allow it use that instead of declaring it again, for example, I'm building an library with composables, and sometime I need to access to `wrap`/`unwrap`.

On my case I described the types: 
https://github.com/pikax/vue-composable/blob/4613b2703d67a40005dcc12230303e74ac48caf0/packages/core/src/utils.ts#L6-L20

**Comment by spaceemotion** [comment]
In my case I would like to use a reactive object (with `isLoading`, `data` and `error`), but because the type information is missing, I had to fall back to individual refs().

**Comment by pikax** [comment]
@spaceemotion what do you mean? can you provide an example of how you would expect it to happen?

**Comment by antfu** [comment]
This seems to be covered in #311

**Comment by LinusBorg** [comment]
Yes we can close it once #311 is merged
