### ISSUE TITLE
make public createLifecycle method

### ISSUE THREAD

**Issue by mdbetancourt** [vuejs/composition-api#259]
I think third packages can use it to create own lifecycle like asyncData or fetch

**Comment by antfu** [comment]
Hi @mdbetancourt, thanks for the proposal. But sorry I can't support it now.

On the one hand, custom options entries are still available in Vue 3 and you can use them alongside Composition API. 

And on the other hand, the main goal of this plugin is to provide Composition API aligning with Vue 3 so that migration could be easier. Expose this API would not help with that. I think it's better to wait and see how Vue 3 handles this. We can follow up with it then.

I am closing this now. Feel free to reopen if there are any updates. Thanks.
