### ISSUE TITLE
how can I get the latest route info by context？

### ISSUE THREAD

**Issue by wulucxy** [vuejs/composition-api#324]
I can't get the latest route info by `ctx.root.$route`，when I trigger url change by `history.pushState`。

```
setup(props, ctx) {
  const { $route, $router } = ctx.root

  // 跳转文件详情页
  const gotoFileDetail = fileId => {
    let nextPath = ''
    console.log('$route.path', $route.path) // this not change
    console.log('ctx.root.$route.path', ctx.root.$route.path) // this.not change also
    console.log('window.locaton', window.location.href)
    if (endsWith($route.path, endStrReg)) {
      // do something
      window.history.pushState({}, '', nextPath) // to change location href
    } else {
      // 否则新建一个路径
      nextPath = path.join($route.path, '/file', String(fileId))
      $router.history.push(nextPath)
    }
  }
}
```

the question is: how can I get the latest $route info?

**Comment by posva** [comment]
> when I trigger url change by history.pushState

If you do that the router won't know the new location. You should avoid it. Note that manually manipulating the history (like `$router.history.push(nextPath)`) is, in general, a bad idea because it creates a disconnection between `$route` and the actual URL shown on the address bad. It is also a private API that shouldn't be used.

As for your question: unfortunately, if you manually modify the URL, you cannot get the latest `$route` information.

I don't know what you are trying to do but please use the appropriate channels to ask questions ([Discord](https://chat.vuejs.org), Stack Overflow)
