### ISSUE TITLE
TypeScript with composition-api: in methods, "this" is Vue, not current instance

### ISSUE THREAD

**Issue by RobertGres** [vuejs/composition-api#338]
### Version
2.6.11

### Reproduction link
[https://codepen.io/robertgres/pen/XWmozGV](https://codepen.io/robertgres/pen/XWmozGV)

### Steps to reproduce
```
import * as vue from '@vue/composition-api'

vue.defineComponent({
  methods: {
    foo() {
       this.baz() // Error
    },
    baz() {}
  },
  mounted() {
     this.foo() // fine
  }
})
```

### What is expected?
No TypeScript errors

### What is actually happening?
TS2339: Property 'baz' does not exist on type 'Vue'.

---
Seems like typings don't take into accout current instance

This fixes given problem (in file types/options.d.ts):

`type DefaultMethods<V, S extends V> =  { [key: string]: (this: S, ...args: any[]) => any };`

instead of:

`type DefaultMethods<V> =  { [key: string]: (this: V, ...args: any[]) => any };`

**Comment by Aaron-Pool** [comment]
@posva I don't think it was correct to mark this as a "duplicate". The error being reported here is that type inference for `this` in the options style API breaks when `defineComponent` is used. The issue you referenced has to do with methods returned by the composition `setup` function not being bound to the consuming function's `this` context.

Could we reopen this? Because I'm also running into this issue, where `defineComponent` is breaking a lot of the type inference in my traditional options methods/computed properties.

**Comment by antfu** [comment]
Hi @Aaron-Pool 

> Because I'm also running into this issue, where defineComponent is breaking a lot of the type inference in my traditional options methods/computed properties.

The code provided in the issue works fine with me. Can you share a minimal reproduce repo of the issue you are facing? Thanks

**Comment by Aaron-Pool** [comment]
@antfu Sure! Thanks for the prompt response. [here you are](https://codesandbox.io/s/type-inference-composition-reproduction-bphs2?file=/src/components/HelloWorld.vue)! As you can see the method in `HelloWorld.vue` has no type inference for `this`. It just says `no property "counter" found on "Vue"`

**Comment by Aaron-Pool** [comment]
Just an fyi, I did a little personal digging, and I think the issue is that `defineComponent` is typed as:
```ts
HasDefined<Props> extends true
      ? ComponentOptionsWithProps<PropsOptions, RawBindings, Props>
      : ComponentOptionsWithProps<PropsOptions, RawBindings>) &
    Omit<Vue2ComponentOptions<Vue>, keyof ComponentOptionsWithProps<never, never>>
```

Where as `ComponentOptionsWithProps` is simply defined as:
```ts
interface ComponentOptionsWithProps<
  PropsOptions = ComponentPropsOptions,
  RawBindings = Data,
  Props = ExtractPropTypes<PropsOptions>
> {
  props?: PropsOptions
  setup?: SetupFunction<Props, RawBindings>
}
```

So, `ComponentOptionsWithProps` is only typing the `props` and `setup` options, and the rest of the typing is simply being inferred as `Vue2ComponentOptions<Vue>`, which is just a generic vue instance, and doesn't attempt to infer typing from the options object at all, if I'm understanding correctly 🤷‍♂️

**Comment by antfu** [comment]
Thanks for investigating and you are right. I am working on it. The type is actually very complicated to do, it may takes more time.

**Comment by Aaron-Pool** [comment]
> Thanks for investigating and you are right. I am working on it. The type is actually very complicated to do, it may takes more time.

No sweat! I am well aware of the mindwrecking typescript can be when you get to complexity of this level. Thanks for looking into it for me 👍
