### ISSUE TITLE
Can't assign value of type T to Ref<T>, because the ref is being detected as Ref<UnwrapRef<T>>

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/composition-api#483]
### Env

`@vue/composition-api@1.0.0-beta.10`

`typescript@4.0.0-dev.20200803`

Same behaviour in `vue@3.0.0-beta.5`

### Expected beaviour (when not using generics)

```ts
function fooNumber (valueT: number) {
  const r = ref(valueT);

  r.value = valueT; // works fine
}
```

### Actual behaviour (with generics)

```ts
function fooGeneric<T> (valueT: T) {
  const r = ref(valueT); // r is Ref<UnwrapRef<T>>

  r.value = valueT; // TS2322: Type 'T' is not assignable to type 'UnwrapRef '.
}

```

![image](https://user-images.githubusercontent.com/15625235/90560944-347f5b00-e1a0-11ea-97b8-d721b0031821.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue-next/issues/1324

**Comment by ssipos90** [comment]
Hi. I don't think this is the same issue as the one you linked. What was your resolution on this?

**Comment by jacekkarczmarczyk** [comment]
It's the same issue and solution is the same as the one in the linked issue

**Comment by ssipos90** [comment]
Given:

```typescript
import { reactive } from '@vue/composition-api';

interface MyState<T> {
  control: number;
  issue: T;
};

// control

const state = reactive<MyState<string>>({
  control: 1,
  issue: 'works'
});

state.issue = 'still works';

// issue
const createState = <T>(initial: T) => {
  const state = reactive<MyState<T>>({
    control: 1,
    issue: initial
  });

  state.issue = initial;

  return state;
};

const state2 = createState('asd');
state2.issue = 'works again';

```

In the control block, the state is fine:
![image](https://user-images.githubusercontent.com/11758652/120803074-d7e10700-c54b-11eb-8a24-fcbe216072ea.png)

However, setting the generic type from the argument, stops working because `state.issue` is not the correct type.
![image](https://user-images.githubusercontent.com/11758652/120803195-f941f300-c54b-11eb-9c9c-fd011ca7f380.png)

Giving the error: `Type 'T' is not assignable to type 'UnwrapRef<T>'. ts(2322)`
Am I missing something?

**Comment by vincerubinetti** [comment]
In my case, I was able to fix the error by using a `shallowRef` instead of a `ref`, per the advice of this comment: https://github.com/vuejs/core/issues/1324#issuecomment-859766527

Though it seems like this wouldn't be a viable solution for the commenter above me.

Here is my reduced example:

```typescript

export const useQuery = <T>(func: () => Promise<T>, defaultValue: T) => {
  const data = shallowRef<T>(defaultValue);
  // const data = ref<T>(defaultValue); // <-- doesn't work

  async function query(): Promise<T> {
    const results = await func();

    data.value = results;

    return results;
  }

  return { query };
};
```

Using a plain `ref` results in an error when trying to assign to `data.value`:

```
 Type 'Awaited<T>' is not assignable to type 'UnwrapRef<T>'.
  Type 'T | (T extends object & { then(onfulfilled: infer F): any; } ? F extends (value: infer V, ...args: any) => any ? Awaited<V> : never : T)' is not assignable to type 'UnwrapRef<T>'.
    Type '(null | undefined) & T' is not assignable to type 'UnwrapRef<T>'.
      Type 'undefined & T' is not assignable to type 'UnwrapRef<T>'.ts(2322)
```

I believe this is related to the issue in this thread.
