### ISSUE TITLE
Alias `vm.$root` with `this.root` to match with Vue 3

### ISSUE THREAD

**Issue by antfu** [vuejs/composition-api#499]
https://github.com/vuejs/vue-apollo/pull/1040#issuecomment-685866246 by @frandiox

**Comment by frandiox** [comment]
@antfu Thanks!

**Comment by pikax** [comment]
Current instance aka vm comes directly from Vue 2 and not related directly with the composition api, because `getCurrentInstance` should be handled with care. 

Adding this would possible introduce breaking changes since `root` is quite common name and it can collide with current component props or data

**Comment by ivansieder** [comment]
@pikax but in this case it would be just to have feature parity with Vue 3's $root and that's where the Composition API should be AFAICT. Right?

**Comment by pikax** [comment]
Not really because the `getCurrentInstance` in v3 gets the internal instance which should not have the user data there.

But `getCurrentInstance` in the plugin returns the public v2 instance, we can return the internal instance (need to look on how to get it), which would be spec compliant, altho with breaking changes

**Comment by antfu** [comment]
One other solution might be to mock the instance of v3 to match with the behaviour. And expose the v2 instance in `getCurrentInstance().ctx`. It will be a breaking change for this plugin through.

**Comment by pikax** [comment]
`getCurrentInstance().ctx` is not actually the public instance, the public instance is found on `getCurrentInstance().proxy` which is *currently* marked as `@internal`

> It will be a breaking change for this plugin through.

Introducing a breaking change, should be alright, implementation wise is my concern, extracting the correct data to construct a similar api, is a bit more annoying :/

**Comment by antfu** [comment]
> extracting the correct data to construct a similar api, is a bit more annoying :/

For me, this plugin is not just only offering the "Composition API" feature but also taking the responsibility of lowering the gap for migration from Vue 2 to 3. I think it's better to be done on our side as we could have better access to internal states, if not, libraries might need to overcome the differences between those versions on their own.

>  the public instance is found on getCurrentInstance().proxy

I am not very familiar with the internal of Vue 3. Is there any reason it's being marked as internal? If it's not desired to be accessed, should we not expose the Vue 2 vm as well? (maybe marked as internal too)
