### ISSUE TITLE
Bug props in composition-api beta 14

### ISSUE THREAD

**Issue by pinghe** [vuejs/composition-api#534]
```
export default {
  props: {
    filter: {
      type: Object,
      default: function() {
        return {
          c1: 'c1',
        }
      },
    },
  },
  setup(props) {
    console.log('props is: ', isRef(props), isReactive(props))
    watch(props, () => {  // error 
      console.log(props)
    }
  }
}
```
beta11:  props is: false true
beta14:  props is: false false //  watch --> error

**Comment by antfu** [comment]
What's the error you have?

**Comment by LinusBorg** [comment]
the `props` argument should be detected as a reactive, but isn't.

That's because we use __ob__ do detect that, and the `props` argument isn't a real Vue.observable, it's "faked":

https://github.com/vuejs/composition-api/blob/3a1d99263c91db45fdf90cbd6bb1da9ed2ff20f1/src/mixin.ts#L85-L86

...and therefore has no __ob__ and is not detected as a reactive object by `isReactive()`
