### ISSUE TITLE
If my component does not have a root node, how can I use Composition-API to get the $el for this component?

### ISSUE THREAD

**Issue by coolqingcheng** [vuejs/composition-api#586]
If my component does not have a root node, how can I use Composition-API to get the $el for this component

If There is a root node, I can use ref, but there is no root node, how can I get the current component's $el information in the Composition API ?

**Comment by antfu** [comment]
An workaround for now (not portable to Vue 3)

```ts
onMounted(()=>{
  getCurrentInstance().$el
})
```

**Comment by coolqingcheng** [comment]
If you're in the Vue3, what should you do about it?
`onMounted(()=>{
  getCurrentInstance().$el
})`
This code is not available

**Comment by LinusBorg** [comment]
In Vue 2, components always have one single root node, so you just use a ref on that element to get it.
In Vue 3, components don't can have multiple root nodes, so there can't be a single `$el`, because *that would be the one single root root node, which might not exist*.

So: also use a ref, and choose the root node that you want to use for it.
