### ISSUE TITLE
Refs in a vue library built with VueCLI are no longer reactive after build

### ISSUE THREAD

**Issue by noook** [vuejs/composition-api#625]
This is issue is probably the same as the #587 but as it lacks of explanation I can't tell if it's the same problem or not.

What's happening is, when I develop the library with a playground, I can inspect in the DevTools that my `ref`s are unwrapped. But when I use it in the real app, every ref appear with a specific form: Every `ref` appear with a `.value` property.

Here are the links and steps to reproduce the bug:

## Library

[Repository link](https://github.com/Hylll/lib-test)

Setup:

+ Run `yarn` to install dependencies
+ Run `yarn serve` to check the main App, and see (in the DevTools) that the ref still works before building the project
+ Run `yarn link` to prepare a symlink of the package so we can try it on the other project
+ Run `yarn build` to build the dist folder (`commonjs` format, and CSS output)

Script code of the Button component:

```ts
import { defineComponent, ref } from '@vue/composition-api';

export default defineComponent({
  name: 'GButton',
  props: {},
  setup() {
    const foo = ref('foo');

    return {
      foo,
    };
  },
});
```

## App

[Repository link](https://github.com/noook/vue-composition-lib-app)

Setup:

+ Run `yarn` to install dependencies
+ Run `yarn link "design-system"` to link the previously installed library
+ Run `yarn serve` to run the project that includes our app
+ Check in the devtools, the property `foo` should have for value the string `foo`, but instead is an object of the form `{ "value": "foo" }`

![image](https://user-images.githubusercontent.com/19751938/103817659-674ec080-5067-11eb-8a71-43f2257d8a68.png)

Steps:

**Comment by antfu** [comment]
Not very familiar with Vue CLI's lib build process, but did it externalize `@vue/composition-api`? If there are two VCA plugin instances in a bundle the reactiveness won't work together. There are quite a few libs using it and works just fine. I think it's more likely a configuration thing rather than a bug of this plugin.

**Comment by pikax** [comment]
This is caused most likely by: `yarn link "design-system"` 

If `design-system` depends on `vue` or `@vue/composition-api` it's dependency will be loaded, making you having two instances of the composition-api running, which you can't have.

**Comment by noook** [comment]
Is there a way to prevent this then ?

By the way, they are noted as `peerDependencies`, so do they install aswell ?

**Comment by pikax** [comment]
> Is there a way to prevent this then ?

This is caused by the `yarn link` and how the module will be resolved, you can try a few things: 
- Remove `node_modules/@vue/composition-api` from your linked library
- don't use `yarn link`

I know those are not ideal, but this problem will happen when you use `vue`, `vue-next` or any library that relies on the exact module instance to be accessed every time

**Comment by noook** [comment]
Alright, now I understand what's the path to the issue resolution.

Concerning the yarn link, is there a better approach ? Does the `npm` equivalent handles better the linking ?
