### ISSUE TITLE
watchEffect needs a Promise<void> override

### ISSUE THREAD

**Issue by lyle45** [vuejs/composition-api#648]
watchEffect type throws an unused promise eslint error as you can see, as it only accepts a CB with void return type

![image](https://user-images.githubusercontent.com/17912606/108815432-23832c80-75bd-11eb-8363-0c20cb11e7ee.png)

**Comment by pikax** [comment]
`watchEffect` gathers dependencies synchronous, having an `async` callback must be used careful because if you access properties after an `await` it won't gather further dependencies.

**Comment by lyle45** [comment]
@pikax Wow, great point! Isn't this problematic for a hook that's used to create sideEffects? 😅 
Is this on the roadmap or a permanent limitation?

**Comment by LinusBorg** [comment]
this is a permanent limitation

**Comment by lyle45** [comment]
would it be able to track dependencies defined in a scoped function?

i.e. writing 

 watchEffect(() => {
    async function fn() {

      await someAsyncPromise();
      if (refToTrack.value) {
        console.log('tracked')
      }
    }
    
    fn();
  });

**Comment by LinusBorg** [comment]
No.

**Comment by darkbasic** [comment]
The official documentation uses async/await in watchEffect: https://vuejs.org/guide/essentials/watchers.html#watcheffect

**Comment by craigcrawfordcts** [comment]
Official doco uses async/await and typescript says its not allowed... So, is it allowed or not...

**Comment by craigcrawfordcts** [comment]
I ended up just using `watch` since it supports await without an issue and for some reason `watchEffect` doesn't seem to automagically track the dependencies of the function being called as stated

I have these props:
```typescript
const props = defineProps<{
  id: string,
  branding?: string | undefined
}>();
```

And the `myAsync` is just a function in a Pinia state store and has its own internal `ref` for `id` and `branding` that are set when `myAsync` is called and then it makes a `fetch` with those refs.

In this setup, this works:
```typescript
watch(props, async (value, oldValue) => {
  if (value.id !== oldValue.id || value.branding !== oldValue.branding ) 
    await myAsync(props.id, props.branding);
});
```

This doesn't (the function is called every time I save a change in a vue file, but the above does not re-call it):
```typescript
watchEffect(() => {
  myAsync(props.id, props.branding);
});
```

Neither does this as TS doesn't like the `Promise<void>` return:
```typescript
watchEffect(() => 
  myAsync(props.id, props.branding)
);
```

Can't use await since it's not an async, also not valid:
```typescript
watchEffect(() => 
  await myAsync(props.id, props.branding)
);
```

So what if we make it an async?
```typescript
watchEffect(async () => 
  await myAsync(props.id, props.branding)
);
```

Nope... Only `watch` works.

**Comment by darkbasic** [comment]
> So, is it allowed or not...

AFAIK it is not allowed because it wouldn't be able to track dependencies.
The documentation is overall very good but this isn't the first case where it's either plain wrong or at least not so clear.

**Comment by n0099** [comment]
https://typescript-eslint.io/rules/no-misused-promises/

**Comment by peitschie** [comment]
> AFAIK it is not allowed because it wouldn't be able to track dependencies. The documentation is overall very good but this isn't the first case where it's either plain wrong or at least not so clear.

If this is truly not allowed (or not recommended), the documented example should be updated to reflect this: https://vuejs.org/guide/essentials/watchers.html#watcheffect

![Image](https://github.com/user-attachments/assets/27fd23d3-edb9-410f-946d-4625bed14f31)

Currently, the docs showcase an example that the typescript typing forbids. It's pretty confusing!

**Comment by pikax** [comment]
> If this is truly not allowed (or not recommended), the documented example should be updated to reflect this: https://vuejs.org/guide/essentials/watchers.html#watcheffect


The docs example [works as expected](https://play.vuejs.org/#eNp9UsFu2zAM/RVCGNAUyGwM2ylIAmxDD91hLdoedahgM4laWRIk2klh+N9LSXXaQ1FfLJKPj49PGsVv76uhR7ES69gE7QkiUu+30urOu0AwQsDdEo6KmgNMsAuugwvuuJC2cTYSkGvddQubhFv8uJzTrSL1lrS9MZyXNpMspIW3pmU6qvhiG1hcwmYLY0oAFIaA0fMBmUUdlSbY4dyevscDkY+run6KznqjGjw402Ko6MXrxrVYNa6r06BYfxvLwGpQpsfpsXCwpvRLSkvhPGkeXSXuRcZNWewIuuuw1YpwBRS4ZZI27ybtui4OsnccEHYsipAjgLW2vicYvnesy2ykKHKkgDqjGdHqYTuOxbZpWtcpTpwfeMRSUGRvdnqfhfGlZcOk4E29NhhuPGnWLcVqtlIKZYw7/su5JDivkXsO2Dx/kn+Kp5ST4pZdwDCgFOcaqbBHKuWr+/944vO5yLv1htFfFO8wOtMnjQX2p7cty/6Ay2qv89PTdv8Qr06ENs5LJaHvlyEFv8O/X6z+Lvdn9Sv3STuJ6RUKMv2P), the only not recommended part is because is very easy to think we are tracking a dependency but it ends up not tracking, as I [expressed in my comment](https://github.com/vuejs/composition-api/issues/648#issuecomment-784012286)


> Currently, the docs showcase an example that the typescript typing forbids. It's pretty confusing!

What does typescript typing forbids? [Seems to be working just fine for me](https://www.typescriptlang.org/play/?jsx=0#code/JYWwDg9gTgLgBAbzgdwIYwMYAsCiAzPAUwxgBo4pC84BfOPKCEOAcgDcBXQlgKB4wgA7AM7wAJulRwAvBSoAeVIICeAPgAUASj5pMuAsRjrUw5YIxwtM1Yh5w4AkfErDIIwjLio0weET3qdvZwAAZYMDBgwgBcAPSxAFbCQmAANqgYhFgQqWKEUAB0MMpgwAJ5BQIgsTAQYhDCsQAkCLX1AJJiBWyoqVw0IUHa9hIwqN29XJ7eqL5yrkLChAVJQlo8NJpAA)

![Image](https://github.com/user-attachments/assets/7651d33f-b243-4035-bf7e-589b9cc4b616)

**Comment by peitschie** [comment]
The types here do not reflect that a promise is an ok return path:

```typescript
export type WatchEffect = (onCleanup: OnCleanup) => void;
export declare function watchEffect(effect: WatchEffect, options?: WatchEffectOptions): WatchHandle;
```

If you have any proper linting enabled to try and catch bugs caused by returning promises where a void is the accepted type, it will flag the example code as incorrect.

The correct type definition for `WatchEffect` should be:
```typescript
export type WatchEffect = (onCleanup: OnCleanup) => Promise<void> | void;
```

I'd be happy to raise a patch if this is not an intentional over-restriction... which is what I was previously assuming it was 🙂

**Comment by peitschie** [comment]
Here's a pretty common lint rule that's used to properly enforce a function explicitly opting into allowing an async function:

```
{
  "rules": {
    "@typescript-eslint/no-confusing-void-expression": "error",
    "@typescript-eslint/no-misused-promises": "error"
  }
}
```

**Comment by craigcrawfordcts** [comment]
> What does typescript typing forbids? [Seems to be working just fine for me](https://www.typescriptlang.org/play/?jsx=0#code/JYWwDg9gTgLgBAbzgdwIYwMYAsCiAzPAUwxgBo4pC84BfOPKCEOAcgDcBXQlgKB4wgA7AM7wAJulRwAvBSoAeVIICeAPgAUASj5pMuAsRjrUw5YIxwtM1Yh5w4AkfErDIIwjLio0weET3qdvZwAAZYMDBgwgBcAPSxAFbCQmAANqgYhFgQqWKEUAB0MMpgwAJ5BQIgsTAQYhDCsQAkCLX1AJJiBWyoqVw0IUHa9hIwqN29XJ7eqL5yrkLChAVJQlo8NJpAA)

I think that design is a little simplistic to show the issue. The examples I shared above causes loss of dependency tracking, as was mentioned earlier by @darkbasic 

In the case of pinia stores, it certainly doesn't work very well. I think instead the Promise should be removed if it has the potential to cause inconsistent behaviour.

**Comment by mitar** [comment]
[Documentation currently nicely states](https://vuejs.org/guide/essentials/watchers#watcheffect):

> watchEffect only tracks dependencies during its synchronous execution. When using it with an async callback, only properties accessed before the first await tick will be tracked.

I think this is pretty good and clearly shows that async callback is supported (and examples above that tip in documentation uses async), but typing does not. So I think this issue should be reopened.

**Comment by mitar** [comment]
I made a new issue for this for Vue 3: https://github.com/vuejs/core/issues/14249
