### ISSUE TITLE
Build into a library and report an error

### ISSUE THREAD

**Issue by junjieit** [vuejs/composition-api#674]
### @vue/composition-api version
1.0.0-rc.6

### Vue version
2.6.11

### Steps to reproduce
1. Create a Vue project.
2. Use `ref` from `@vue/composition-api`.
```
<template>
    <div>{{ text }}</div>
</template>
<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api'

export default defineComponent({
  setup() {
    const text = ref('test ref')
    return {
      text
    }
  }
})
</script>
```
3. Use `vite` or `vue-cli` to build into a library.

### What is Expected?
get `<div>test ref</div>`

### What is actually happening?
get `<div>{ "value": "test ref" }</div>`

**Comment by pikax** [comment]
@junjieit That error looks to happen because your library is shipping the `vue` instance with your library.

Please check examples https://github.com/vuejs/composition-api/issues/625 https://github.com/vuejs/composition-api/issues/587 

--- 

If you have further questions please refer to our [Discord](https://vue.land) where you can find more help.
