### ISSUE TITLE
NuxtCompositionApi: When send computed props as dynamic value to class is not working on first render

### ISSUE THREAD

**Issue by Shugar** [vuejs/composition-api#695]
Hey!

I'm trying to pass a value to a component dynamic class, but on first render it returns wrong class somehow, while other values are correct. 

Following code gets data from server using GraphQL and composition-api. Then I return values as variables using computed and pass them to template.

`useGetPages function`

![image](https://user-images.githubusercontent.com/5647725/118380041-bee9d380-b5e7-11eb-8fc4-b9b28c0c10ca.png)

`BaseHero.vue code`

![image](https://user-images.githubusercontent.com/5647725/118380000-6dd9df80-b5e7-11eb-8cd1-4e45f6c508d2.png)

`BaseHero.vue template`

![image](https://user-images.githubusercontent.com/5647725/118380036-b42f3e80-b5e7-11eb-807a-730658e5c5eb.png)

`console.log(currentPage, title, description, isBlog, heightClass) in BaseHero.vue before return function`

![image](https://user-images.githubusercontent.com/5647725/118380173-826aa780-b5e8-11eb-8e3d-8605b1288ecc.png)

`iTerm terminal console - console.log(currentPage, title, description, isBlog.value, heightClass.value)`

![image](https://user-images.githubusercontent.com/5647725/118380363-d75aed80-b5e9-11eb-82b1-856eaf03b235.png)

When I'm trying to put `heightClass` in template it returns current value, but in dynamic class it still default value. Occurs only on first render, then when I switch between pages it works perfectly and gets expected result.

What am I doing wrong?

**Comment by pikax** [comment]
Please provide a reproduction. Please don't share images if you are only showing code, images don't allow copy&paste, only use images to present an IDE error or something similar, but always provide the code as text.

Seeing the `Nuxt SSR` on the console log, is it running on SSR, if it is please create the issue on NuxtCompositionApi project. If the issue is only on this plugin we can reopen the issue.
