### ISSUE TITLE
Type 'T' does not satisfy the constraint 'object'.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [vuejs/composition-api#698]
Generic arguments are not working with Vue composition API specific functions .i.e. `reactive`, `ref`, `toRefs`, etc.

```
import { reactive } from '@nuxtjs/composition-api';
import { toRefs } from '@vueuse/core';

export const useForm = <T>(Dto: new () => T) => {
  const data: T = reactive({ ...new Dto() } as any); // <-- Removing as any will give "Argument of type 'T' is not assignable to parameter of type 'object'."

  const setForm = (Data: new () => T) => {
    for (const [key, value] of Object.entries(Data)) {
      (data as any)[key] = value;
    }
  };

  return {
    data: toRefs<T>(data), <-- specifying <T> gives "Type 'T' does not satisfy the constraint 'object'."
    setForm
  };
};

```

Any fix or workaround for it?

**Comment by pikax** [comment]
There's no `@vue/composition-api` import.

The issue there, is because you are casting it to `as any`, you are casting it because `T` can be anything and `reactive` **only** works with `object`, that's the reason of the error.

`reactive<T>` is different than `T`, make sure you read [reactive](https://v3.vuejs.org/api/basic-reactivity.html#reactive)

```ts
export const useForm = <T extends object>(Dto: new () => T) => {
  const data = reactive({ ...new Dto() })  as T; // casting as T to prevent the type `UnwrapRef<T>`
```
--- 

Please use issues for bugs or incorrect behaviour, for questions use [discord](https://vue.land) or [forum](https://forum.vuejs.org/).

**Comment by UsmanJavedAttari** [comment]
> There's no @vue/composition-api import.
I am using Vue 2.

> The issue there, is because you are casting it to as any, you are casting it because T can be anything and reactive only works with object, that's the reason of the error.
`<T extends object>` solves the issue.

Thanks,
