### ISSUE TITLE
triggerRef stopped working with watch-multiple

### ISSUE THREAD

**Issue by gkubisa** [vuejs/composition-api#805]
Since [@vue/composition-api@1.1.2](https://github.com/vuejs/composition-api/releases/tag/v1.1.2), `triggerRef` stopped triggering `watch` when watching an array of shallow refs. It appears to be caused by https://github.com/vuejs/composition-api/pull/791.

Here's a [code sandbox](https://codesandbox.io/s/vue-triggerref-and-watch-multiple-bug-jxpii) demonstrating the issue. If you switch `@vue/composition` back to version 1.1.1, the same example will work correctly and consistently.

**Comment by webfansplz** [comment]
@gkubisa @antfu I think this is the right behavior, aligned with Vue3. 

[vue3 CodeSandbox](https://codesandbox.io/s/silent-silence-zumnm?file=/src/App.vue)

**Comment by webfansplz** [comment]
But they have different behaviors when value changed and set `deep`, I will take a pr to fix it

[vue2 CodeSandbox](https://codesandbox.io/s/vue-triggerref-and-watch-multiple-bug-forked-txmq2?file=/src/App.vue)

[vue3 CodeSandbox](https://codesandbox.io/s/silly-shtern-u60rm?file=/src/App.vue)

**Comment by webfansplz** [comment]
@antfu 

These are not the only problems. The following also don't work:

```ts
 const counter = shallowRef({ count: 0 });
    const counterOne = shallowRef(0);
    const counterMany = shallowRef(0);
    function trigger() {
      counter.value = { count: 0 };
    }

    //   should not trigger,but it triggered
    watch(counter, () => counterOne.value++);

```
[CodeSandbox](https://codesandbox.io/s/vue-triggerref-and-watch-multiple-bug-forked-kbb03?file=/src/App.vue:392-671)

Vue3 fix some issues about that,we don't aligned or we didn't find or fix them.

I'm not sure how we should fix it now, because some of it involves relatively big changes.[such as :](https://github.com/vuejs/vue-next/commit/390589ec6d977675c5cef2807fbf3e930a25eef0#diff-f1807b09401aa4291cc300396b66db297bcd4b501ae86d65f35ab72a3efb9db8)
