### ISSUE TITLE
watch deep object with circular reference error

### ISSUE THREAD

**Issue by muuyao** [vuejs/composition-api#829]
https://codesandbox.io/s/wizardly-hermann-kumgx?file=/src/App.js
```js
import { defineComponent, h, watch } from "@vue/composition-api";

class TreeNode {
  constructor() {
    this.name = "test";
    this.root = this;
  }
}

const Field = defineComponent({
  props: ["treeNode"],
  setup(props) {
    watch(
      () => props.treeNode,
      (val) => {
        console.log("val", val);
      },
      { deep: true }
    );
    return () => h("div", [props.treeNode.name]);
  }
});

export default defineComponent({
  name: "home",
  setup() {
    return () => h("div", [h(Field, { props: { treeNode: new TreeNode() } })]);
  }
});
```
RangeError: Maximum call stack size exceeded

**Comment by edwardnyc** [comment]
According to my trivial attempt, this should only occur on 'createElement', because the 'props' attribute is not reactive.

I tried two ways

1. There are too many `createElement ` attributes to handle easily
2. The `initsetup` stage deep reactive will result in additional calls to `getter`

Looking forward to the solutions of excellent predecessors 👀
